### ISSUE TITLE
 Pin memory thread exited unexpectedly

### ISSUE THREAD

**Issue by zhongxiaj** [octree-nn/ocnn-pytorch#11]
it is weird that when I run the command :python classification.py --config configs/cls_m40_hrnet.yaml SOLVER.alias time
 Pin memory thread exited unexpectedly,
but when I change the  Lenet, everything is ok.

**Comment by wang-ps** [comment]
Sorry, I have not noticed this issue before.

**Comment by zhongxiaj** [comment]
> Sorry, I have not noticed this issue before.

Thanks
