### ISSUE TITLE
Pre-trained model weights?

### ISSUE THREAD

**Issue by harryseely** [octree-nn/ocnn-pytorch#16]
I am interested in using transfer learning for OCNN-LeNet. Would you be able to provide a pre-trained model (e.g., .t7, .pth) file? I can't seem to find one online...

**Comment by wang-ps** [comment]
The pretrained models can be found in the documentation:  https://ocnn-pytorch.readthedocs.io/en/latest/index.html

![image](https://user-images.githubusercontent.com/7525130/217690042-67d78020-74ac-460c-95a3-2c3495d7590e.png)

**Comment by harryseely** [comment]
Amazing thank you!
