### ISSUE TITLE
key advantages of key advantages

### ISSUE THREAD

**Issue by samanemami** [octree-nn/ocnn-pytorch#2]
What are the key advantages of your library in comparison to the [microsoft](https://github.com/microsoft)/[O-CNN](https://github.com/microsoft/O-CNN)?
I could not find any related description in the documentation that tells the difference between these two libraries.

Thank you

**Comment by wang-ps** [comment]
`octree-nn/ocnn-pytorch` is based on **pure** PyTorch, while the core of `microsoft/O-CNN` is based on C++/CUDA. 
Therefore,   `octree-nn/ocnn-pytorch` is easier to build and more compatible.

**Comment by samanemami** [comment]
Thank you.

Yes, indeed is easier to build and compatible with different OS.
So, the main performance (In terms of building sparse convolutional layers) of both is the same?

**Comment by wang-ps** [comment]
The functionality is the same. 
The memory consumption is similar, and as for speed, `octree-nn/ocnn-pytorch` runs even faster.

**Comment by samanemami** [comment]
Perfect, thanks
