### ISSUE TITLE
Regarding downsampling layers in ounet and unet

### ISSUE THREAD

**Issue by raoshashank** [octree-nn/ocnn-pytorch#24]
I notice that the downsampling layers in the ounet and unet models use ConvBnRelu as the downsamplers rather than pooling, which is typically used in such dense prediction/reconstruction networks to extract hierarchical features. Is there some relation between the two operations due to the structure of the octree itself?

**Comment by wang-ps** [comment]
The stride of ConvBnRelu is **2** for downsampling; a pooling layer with a stride of 2 can also be used.  The ConvBnRelu has trainable parameters, it can result in slightly better preformance than pooling.
