### ISSUE TITLE
Is it possible to construct an octree for a CT(Computed Tomography) image(e.g., 512^3 size)?

### ISSUE THREAD

**Issue by pILLOW-1** [octree-nn/ocnn-pytorch#28]
O-CNN constructs an octree based on point cloud. From my perspective, any high-dimensional data (e.g. dim>=3) could also has its octree through a somewhat different construction. For example, my data is a three-dimensional computed tomography image which has a size of 512^3. I want to borrow the idea of O-CNN and construct an octree for CT images. Is it possible?

**Comment by juanprietob** [comment]
was it possible?
