### ISSUE TITLE
Octree; 'NoneType' object has no attribute 'device'

### ISSUE THREAD

**Issue by samanemami** [octree-nn/ocnn-pytorch#3]
When I try to build an OCTree, it returns the following error.

```Python
oc_tree = Octree(depth=8, full_depth=2)
oc_tree.xyzb(8)
```
```log
'NoneType' object has no attribute 'device'
```

The oc_tree has the following type
```log
ocnn.octree.octree.Octree
```

**Comment by samanemami** [comment]
As far as I understand, we have to build oc_tree after calling the class and the only method that works fine for this matter is  `build_octree(point)` Cause in any case we have to feed the octree with the points.

But there is a conflict between the size when applying the voxel with built octree

```Python
oc_tree = ocnn.octree.Octree(depth=8)
oc_tree.build_octree(point)
ocnn.nn.octree2voxel(tensor_cloud, oc_tree, 8)
```

```log
RuntimeError: shape mismatch: value tensor of shape [841348, 3] cannot be broadcast to indexing result of shape [109320, 3]
```

**Comment by wang-ps** [comment]
please refer to the example files in this folder https://github.com/octree-nn/ocnn-pytorch/blob/master/projects/datasets to figure out the usage of `build_octree`

**Comment by samanemami** [comment]
Thanks, But I could not find related examples to `build_octree`, they used the Point class only.
I think we can relate this issue to #5

**Comment by wang-ps** [comment]
Please first run the provided examples following the tutorials like [Classification](https://ocnn-pytorch.readthedocs.io/en/latest/notes/classification.html), [Segmentation](https://ocnn-pytorch.readthedocs.io/en/latest/notes/segmentation.html)
