### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by cama36** [octree-nn/ocnn-pytorch#32]
Hi, thank you very much for your work! As we all know, the deployment of sparse convolution consistently is a very difficult problem.But  in o-cnn all the ops are pytorch supported, so I would like to ask you if you have tried to export o-cnn to onnx? and if so, I would very much appreciate if you could provide an example, thanks!

**Comment by wang-ps** [comment]
Sorry I have not tried to export o-cnn to onnx. 
Theoretically, it would be easy, since ocnn is implemented with pure Pytorch.
