### ISSUE TITLE
OCNN CUDA-ops

### ISSUE THREAD

**Issue by ChunyuFeng** [octree-nn/ocnn-pytorch#34]
Thanks for your great job! 
I'm working on model deployment on jetson agx orin by tensorRT, and some octree ops (octree-conv/octree-deconv etc.) are used in my model. And I'm wondering that are those ops having a CUDA version? 
Thanks again!

**Comment by wang-ps** [comment]
The original version of `ocnn` was implemented with CUDA. Hope it may be helpful to you.

https://github.com/microsoft/O-CNN
