### ISSUE TITLE
Convolutional layer dimension

### ISSUE THREAD

**Issue by samanemami** [octree-nn/ocnn-pytorch#4]
As I am seeing, this library only uses the 1D Conv layer in the module.
Is there any other implementation with higher dimensions for the layers?

**Comment by samanemami** [comment]
Thank you
But could you please explain it in the code?

I can not understand how would it be a 3D layer as the input has not have four dimensions!

**Comment by wang-ps** [comment]
Please read our [paper](https://wang-ps.github.io/O-CNN_files/CNN3D.pdf) and [Slides](https://1drv.ms/p/s!Ar9egoTYLACXkCw4HOaEI4P3UG2k?e=fb2A3R) to understand the Octree-based sparse convolution.
