### ISSUE TITLE
Clarification on ocnn.octree.merge_octrees Functionality

### ISSUE THREAD

**Issue by kankanzheli** [octree-nn/ocnn-pytorch#41]
Dear OCNN Team,

I hope this message finds you well. I'm currently using OCNN in a reinforcement learning project, and I have a question regarding the ocnn.octree.merge_octrees function.

If I use ocnn.octree.merge_octrees to merge octrees that come from completely independent environments (with no spatial or contextual relationship between them), will this merging process affect the independence of each original octree? Specifically, does merging these octrees lead to any loss of information or introduce interdependence that might affect how the octrees are interpreted individually?

I would greatly appreciate your insights on this matter, as maintaining the integrity of each independent environment's data is crucial for my project.

Thank you for your support.

**Comment by wang-ps** [comment]
No, this operation does not affect the independence of each octree. It just concatenates a batch of octrees for convenient batch processing.
