### ISSUE TITLE
Query Regarding kernel_size Parameter in OctreeConv

### ISSUE THREAD

**Issue by kankanzheli** [octree-nn/ocnn-pytorch#43]
Hi,

I am currently working with the OCNN library and attempting to implement the OctreeConv layer in my project. I encountered an issue where specifying kernel_size=[5] results in a ValueError: Unsupported kernel 555.

Could you please clarify the valid range of values for the kernel_size parameter in OctreeConv? It would be helpful to know which values are supported to ensure compatibility with my setup.

Thank you for your assistance!

Best regards, Zhao Wentao

**Comment by wang-ps** [comment]
<img width="542" alt="image" src="https://github.com/user-attachments/assets/e2a9b3fc-9244-476d-9529-ac86223d21ca">
please refer to the documents for detailed explanations. The kernel 555 is not implemented in this codebase.

**Comment by kankanzheli** [comment]
kernel size = [3] means the kernel size is [3 3 3]?

**Comment by wang-ps** [comment]
yes
