### ISSUE TITLE
octree upsample issue for hrnet

### ISSUE THREAD

**Issue by harryseely** [octree-nn/ocnn-pytorch#8]
Getting an error when testing HRNet (ResNet and LeNet both work with exact same code):

`out = ocnn.nn.octree_upsample(out, octree, d, self.nempty)
AttributeError: module 'ocnn.nn' has no attribute 'octree_upsample'`

It looks like octree_upsample does not exist in ocnn.nn

I think this might be a typo because I can't find any other instances of octree_upsample in the source code beyond its mention in the code shown above within the HRNet.

Hopefully this is an easy fix as I am keen to try out HRNet!

Thanks!

**Comment by wang-ps** [comment]
Thanks for figuring out this issue. I have fixed it. Please pull the latest code and reinstall `ocnn` to have a try.
