### ISSUE TITLE
when i run the code： “python classification.py --config configs/cls_m40_hrnet.yaml SOLVER.alias time”，  KeyError: 'Non-existent config key: DATA.test.flip' 

### ISSUE THREAD

**Issue by zhongxiaj** [octree-nn/ocnn-pytorch#9]
KeyError: 'Non-existent config key: DATA.test.flip'

**Comment by wang-ps** [comment]
Please update the package `thsolver` via the following command and try again: `pip install -U thsolver`

**Comment by zhongxiaj** [comment]
> Please update the package `thsolver` via the following command and try again: `pip install -U thsolver`

thanks for your great work and quickly reply, is there any guide line for me to  organize  my own datasets?  thanks

**Comment by wang-ps** [comment]
There are several examples in this folder, may it be helpful for you.
https://github.com/octree-nn/ocnn-pytorch/tree/master/projects/datasets

**Comment by zhongxiaj** [comment]
> There are several examples in this folder, may it be helpful for you. https://github.com/octree-nn/ocnn-pytorch/tree/master/projects/datasets

thank you very much
